name: Deploy to CloudLaunch VPS

on:
  push:
    branches: [cloudlaunch_deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Copy Code to VPS
      run: |
        rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}

    - name: Build and Deploy Docker Container
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        docker stop container-cloudlaunch || true && docker rm container-cloudlaunch || true
        docker rmi image-cloudlaunch:latest || true
        docker-compose build
        docker-compose up -d
        EOF
